name = "ig-jsx"
compatibility_date = "2023-01-01"
main = "workers-site/index.js"
workers_dev = true

[site]
bucket = "./assets"


[vars]
ENVIRONMENT = "dev"

[env.staging]
workers_dev = false
route = "staging.gramica.online/*"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
workers_dev = false
route = "gramica.online/*"

[env.production.vars]
ENVIRONMENT = "production"
  
