name: Cloudflare-Production
on:
  push:
    tags: prod

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Production Cloudflare Worker
    environment: production
    steps:
      - uses: actions/checkout@v3 
      - name: install dependencies
        run: 'npm install'
      - name: deploy using wrangler 
        run: 'npm run deploy:prod'
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
