name: Cloudflare-Staging
on:
  push:
    tags: staging

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Staging Cloudflare Worker
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: 'npm install'
      - name: deploy using wrangler 
        run: 'npm run deploy:staging'
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
          CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}